name: Update deployment

on:
  release:
    types:
      - created

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Send update request to VPS
        env:
          UPDATE_TOKEN: ${{ secrets.UPDATE_TOKEN }}
          UPDATE_URL: ${{ secrets.UPDATE_URL }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $UPDATE_TOKEN" \
            "$UPDATE_URL?image=luisfadini/personal-website"

      - name: Create GitHub deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "main",
              "environment": "production",
              "transient_environment": true,
              "auto_merge": false,
              "required_contexts": []
            }'
