name: Update deployment

on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - Build and push Docker image
    branches:
      - main
    types:
      - completed

jobs:
  update-deployment:
    if: >
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Send update request to VPS
        env:
          UPDATE_TOKEN: ${{ secrets.UPDATE_TOKEN }}
          UPDATE_URL: ${{ secrets.UPDATE_URL }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $UPDATE_TOKEN" \
            "$UPDATE_URL?image=luisfadini/personal-website"

      - name: Create GitHub deployment
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "main",
              "environment": "production",
              "transient_environment": false,
              "auto_merge": false,
              "required_contexts": []
            }')

          echo "DEPLOYMENT_ID=$(echo "$response" | jq -r .id)" >> $GITHUB_ENV

      - name: Mark deployment successful
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
            -d '{
              "state": "success",
              "environment_url": "https://luisfadini.com"
            }'
      - name: Mark deployment failed
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
            -d '{
              "state": "failure"
            }'
